FROM golang:latest

WORKDIR /app

ARG apt_cacher
RUN if [[ -z "$apt_cacher" ]] ; then echo "Acquire::http { Proxy \"$apt_cacher\"; };" >> /etc/apt/apt.conf.d/01proxy ; fi

RUN apt update \
    && apt install -y imagemagick
