version: '3'

env:
  NAME: blog_support

dotenv: ['.env']

tasks:
  build_dev:
    cmds:
      - | 
        docker buildx build \
          --file Dockerfile.dev \
          --platform linux/arm64 \
          --build-arg arch=arm64 --build-arg apt_cacher=${APT_CACHER} \
          --push -t ${REGISTRY}/${NAME}_dev:latest .
    silent: true
  build:
    cmds:
      - | 
        docker buildx build \
          --file Dockerfile \
          --platform linux/arm64 \
          --build-arg arch=arm64 \
          --push -t ${REGISTRY}/${NAME}:latest .
    silent: true
